<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CodePolicies.aspx.cs" Inherits="AgencyWebApp.CodePolicies" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
<table border="0">
    <tr>
    <td>
    <asp:Label ID="LabelFindModel" runat="server" Text="Label">Страна</asp:Label><asp:TextBox ID="TextBoxFindPolicy" runat="server"></asp:TextBox>
        <asp:Button ID="ButtonFindPolicy" runat="server" Text="Найти" OnClick="ButtonFindPolicy_Click" />
    <br />        
        <asp:GridView ID="GridViewPolicy" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GridViewPolicy_RowCancelingEdit" 
            OnRowDeleting="GridViewPolicy_RowDeleting" 
            OnRowEditing="GridViewPolicy_RowEditing" 
            OnRowUpdating="GridViewPolicy_RowUpdating" PageSize="15" 
            OnPageIndexChanging="GridViewPolicy_PageIndexChanging"
            Caption="Страховка" 
            EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Код" SortExpression="Id" />
                <asp:TemplateField HeaderText="Клиент" SortExpression="ClientId">
                <EditItemTemplate>
                    <asp:DropDownList ID="ClientDropDownList" runat="server" DataSourceID="SqlDataSourceClient" DataTextField="fullName" DataValueField="id" SelectedValue='<%# Bind("id") %>'>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                 <asp:Label ID="ClientId" runat="server"  Text='<%# Eval("Client.FullName") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
                <asp:TemplateField HeaderText="Дата регистрации" SortExpression="RegisteredAt">
                    <EditItemTemplate>
                        <asp:Calendar ID="RegistredAtCalendar" runat="server" SelectedDate='<%# Bind("RegistredAt") %>'></asp:Calendar>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="RegistredAt" runat="server" Text='<%# Eval("RegistredAt") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Окончание" SortExpression="Finish">
                    <EditItemTemplate>
                        <asp:Calendar ID="FinishCalendar" runat="server" SelectedDate='<%# Bind("Finish") %>'></asp:Calendar>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Finish" runat="server" Text='<%# Eval("Finish") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Тип" SortExpression="TypeOfInsuranceId">
                <EditItemTemplate>
                    <asp:DropDownList ID="TypeOfInsuranceDropDownList" runat="server" DataSourceID="SqlDataSourceTypeOfInsurance" DataTextField="name" DataValueField="id" SelectedValue='<%# Bind("id") %>'>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                 <asp:Label ID="TypeOfInsuranceId" runat="server"  Text='<%# Eval("TypeOfInsurance.Name") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            </Columns>
            
    </asp:GridView>
        </td>
        <td>
        <strong>Добавить:</strong>
            <br />
            Клиент
           <asp:DropDownList ID="ClientDropDownList" DataSourceID="SqlDataSourceClient" DataValueField="id" DataTextField="fullName" runat="server"></asp:DropDownList>
            <br />
            <asp:label runat="server">Дата регистрации:</asp:label><asp:Calendar ID="TextBoxRegisteredAt" runat="server"></asp:Calendar>
            <br />
            <asp:label runat="server">Дата окончания:</asp:label><asp:Calendar ID="TextBoxFinish" runat="server"></asp:Calendar>
            <br />
            Тип
           <asp:DropDownList ID="TypeOfInsuranceDropDownList" DataSourceID="SqlDataSourceTypeOfInsurance" DataValueField="id" DataTextField="name" runat="server"></asp:DropDownList>
        </td>
        <td>
            <asp:Button ID="ButtonAddPolicy" runat="server" Text="Добавить" OnClick="ButtonAddPolicy_Click" />

        </td>
</tr>
</table>
    <asp:SqlDataSource ID="SqlDataSourceClient" runat="server" 
        ConnectionString="<%$ ConnectionStrings:AgencyConnectionString %>" 
        SelectCommand="SELECT [id], [fullName] FROM [Clients]">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceTypeOfInsurance" runat="server" 
        ConnectionString="<%$ ConnectionStrings:AgencyConnectionString %>" 
        SelectCommand="SELECT [id], [name] FROM [TypeOfinsurances]">
    </asp:SqlDataSource>
    </asp:Content>
